/**
 * Script to generate embedded-packs.ts with inlined JSON data.
 *
 * This script reads all knowledge pack JSON files and generates a TypeScript
 * file with the data embedded as JavaScript objects. This ensures the knowledge
 * packs work correctly when bundled by consumer applications.
 *
 * Run with: npx tsx scripts/generate-embedded-packs.ts
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';

const PACKS_DIR = join(import.meta.dirname, '../knowledge/packs');
const OUTPUT_FILE = join(import.meta.dirname, '../src/knowledge/embedded-packs.ts');

function camelCase(str: string): string {
  return str
    .replace(/\.json$/, '')
    .replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
    .replace(/-/g, '');
}

function generateEmbeddedPacks(): void {
  console.log('Generating embedded knowledge packs...');

  // Validate packs directory exists
  if (!existsSync(PACKS_DIR)) {
    console.error(`Knowledge packs directory not found: ${PACKS_DIR}`);
    process.exit(1);
  }

  const packFiles = readdirSync(PACKS_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort();

  // Validate at least one pack exists
  if (packFiles.length === 0) {
    console.error(`No knowledge pack JSON files found in: ${PACKS_DIR}`);
    process.exit(1);
  }

  console.log(`Found ${packFiles.length} knowledge packs`);

  const imports: string[] = [];
  const exports: string[] = [];

  for (const file of packFiles) {
    const packPath = join(PACKS_DIR, file);
    const packName = basename(file, '.json');
    const varName = camelCase(packName);

    try {
      // Read and parse the JSON to validate it
      const content = readFileSync(packPath, 'utf-8');
      const data = JSON.parse(content);

      // Generate inline data (use JSON.stringify for packName to escape special chars)
      imports.push(`const ${varName} = ${JSON.stringify(data)} as const;`);
      exports.push(`  { name: ${JSON.stringify(packName)}, data: ${varName} },`);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`Failed to process knowledge pack "${file}" at ${packPath}: ${message}`);
      process.exit(1);
    }
  }

  const output = `/**
 * Embedded Knowledge Packs (Auto-generated)
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated by scripts/generate-embedded-packs.ts
 *
 * Knowledge packs are embedded at build time as JavaScript objects.
 * This allows bundlers to include knowledge packs without requiring
 * filesystem access at runtime.
 *
 * @see {@link ../../docs/adr/003-knowledge-enhancement.md ADR-003: Knowledge Enhancement System}
 */

/* eslint-disable */

// Inline knowledge pack data
${imports.join('\n\n')}

/**
 * All embedded knowledge packs as raw data.
 * Each pack is either an array of entries or an object with a \`rules\` property.
 */
export const EMBEDDED_PACKS: Array<{ name: string; data: unknown }> = [
${exports.join('\n')}
];
`;

  writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`Generated ${OUTPUT_FILE}`);
}

generateEmbeddedPacks();
